### ISSUE TITLE
Acompanhamento reuniões SISOR/SIGPLAN

### ISSUE THREAD

**Issue by gabrielbdornas** [splor-mg/atividades#149]
## Atividades pendentes

- [ ] Acesso board GitLab @gabrielbdornas - Listado [neste issue](https://github.com/splor-mg/reunioes/issues/59).
- [ ] Levantamento de pontos de impacto caso GRP não seja implantado - Listado [neste issue](https://github.com/splor-mg/reunioes/issues/59).
- [ ] Entender quais tecnologias utilizadas no desenvolvimento?  - Listado [neste issue](https://github.com/splor-mg/reunioes/issues/59).
- [ ] Entender portaria 710 (UA - Unidade Administrativa) e a carga baseada na mesma - Listado [neste issue](https://github.com/splor-mg/reunioes/issues/59).
- [ ] Leitura [Miro](https://miro.com/app/board/uXjVKvRXkSk=/) e histórico (boards versionados) - Listado [neste issue](https://github.com/splor-mg/reunioes/issues/60).

## Atas de Reunião

- [Reunião review e retrospectiva Sprint 07 SigPlan - 17/10/2024](https://github.com/splor-mg/reunioes/issues/58).
- [Reunião SigPlan - 16/10/2024](https://github.com/splor-mg/reunioes/issues/59).
- [Reunião Escrita - Especificação do planejamento SISOR/SIGPLAN - 22/10/2024](https://github.com/splor-mg/reunioes/issues/60).
