### ISSUE TITLE
Acompanhamento reuniões AID/SPLOR

### ISSUE THREAD

**Issue by gabrielbdornas** [splor-mg/atividades#151]
### Descrição

Ações pendentes listadas nas reuniões de equipe AID e ou SPLOR

### Lista de atividades e/ou correções

- [ ] Conversar com Carol e equipe sobre trabalho mensagens de erro (Carol retorna de férias dia 18/11/2024) - Listada [neste issue](https://github.com/splor-mg/reunioes/issues/61).
- [ ] Levantamento de banco de ideias para projetos no próximo ano - Listada [neste issue](https://github.com/splor-mg/reunioes/issues/61).
- [x] Conversar com a equipe da Rita (Rodolfo) para entender trabalho e impactos da saída de dois funcionários - Listada [neste issue](https://github.com/splor-mg/reunioes/issues/64).

### Atas de Reunião

- [[31/10/2024] Reunião Gerencial SPLOR](https://github.com/splor-mg/reunioes/issues/64).
- [[28/10/2024] Reunião Gerencial AID](https://github.com/splor-mg/reunioes/issues/61).
- [[16/12/2024] Reunião Gerencial AID](https://github.com/splor-mg/reunioes/issues/81).
- [[16/12/2024] Alinhamento Carlos](https://github.com/splor-mg/reunioes/issues/82).

**Comment by gabrielbdornas** [comment]
Conversar com equipe Rita iniciadas.

**Comment by gabrielbdornas** [comment]
Cheguei à conclusão de que este tipo de Issue não funciona.

O ideal, se for o caso, é documentar a reunião e abrir sub-issues para demandas que aparecerem.
